name: Draft release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: useblacksmith/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install
        run: poetry install
        working-directory: lib/sycamore
      - name: Copy README
        working-directory: lib/sycamore
        run: cp ../../README.md README.md
      - name: build
        run: poetry build
        working-directory: lib/sycamore
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            lib/sycamore/dist/*.tar.gz
